primary:
  initdb:
    scripts:
      init.sql: |
        CREATE USER ejbca WITH PASSWORD 'ejbca2123' CREATEDB;
        CREATE DATABASE ejbca OWNER ejbca;
        CREATE USER keycloak WITH PASSWORD 'keycloak' CREATEDB;
        CREATE DATABASE keycloak OWNER keycloak;
        CREATE USER securityattributesprovider WITH PASSWORD 'securityattributesprovider' CREATEDB;
        CREATE DATABASE securityattributesprovider OWNER securityattributesprovider;
        CREATE USER onboarding WITH PASSWORD 'onboarding' CREATEDB;
        CREATE DATABASE onboarding OWNER onboarding;
        CREATE USER usersroles WITH PASSWORD 'usersroles' CREATEDB;
        CREATE DATABASE usersroles OWNER usersroles;
        CREATE USER identityprovider WITH PASSWORD 'identityprovider' CREATEDB;
        CREATE DATABASE identityprovider OWNER identityprovider;
        CREATE USER authenticationprovider WITH PASSWORD 'authenticationprovider' CREATEDB;
        CREATE DATABASE authenticationprovider OWNER authenticationprovider;
